version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t vladchudov/circleci:$TAG .
          docker login -u vladchudov -p $D_P
          docker push vladchudov/circleci:$TAG
  test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - run:
          export
          date 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
